Ignore fsck badTimezone issues
When the transfer.fsckObjects configuration is set various vim-script
repositories fail to clone/update. The reason is that they contain
commits that git finds to be broken:
  Plugin vim-scripts/genutils
  $ git clone --recursive 'https://github.com/vim-scripts/genutils.git' 'genutils'
  > Cloning into 'genutils'...
  > error: object e30cc0c3cd333bea3df352041cf51943c548d2e5: badTimezone: invalid author/committer line - bad time zone
  > fatal: fsck error in packed object
  > fatal: index-pack failed

With this change we instruct Vundle to ignore this specific error and
just continue.